[package]
authors = ["Praveen Perera <praveen@avencera.com>"]
edition = "2021"
license = "Apache-2.0"
name = "rustywind_core"
version = "0.21.1"
homepage = "https://github.com/avencera/rustywind"
repository = "https://github.com/avencera/rustywind"
documentation = "https://docs.rs/rustywind"
description = "A CLI to sort tailwind CSS classes"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# utils
itertools = { workspace = true }
once_cell = { workspace = true }

# string matching
aho-corasick = "1.0"
regex = { workspace = true }

# logging
env_logger = "0.11"
log = "0.4"

# faster hashmap
ahash = { workspace = true }

# parallel
rayon = "1.5"

# http
ureq = "2.9"

# errors
eyre = "0.6"

# json parsing
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustls = { version = "0.22" }
anstyle = "1.0.1"

[dev-dependencies]
pretty_assertions = "1.4"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
strip = true
